### PR TITLE
Enforced login with TAMU mail id

### PR DESCRIPTION
**Pull request by AkshayeAnithaPradeep**

### CODE REVIEW

**Comment by rawatakhilesh** [comment]
This post presents some ideas:
https://medium.freecodecamp.org/how-to-securely-store-api-keys-4ff3ea19ebda

**Comment by AkshayeAnithaPradeep** [comment]
> This post presents some ideas:
> https://medium.freecodecamp.org/how-to-securely-store-api-keys-4ff3ea19ebda

@rawatakhilesh Thanks for pointing this out. Will look into it.

**Comment by rawatakhilesh** [comment]
Okay. So, are you going to push the changes to this branch or a new one?

> > This post presents some ideas:
> > https://medium.freecodecamp.org/how-to-securely-store-api-keys-4ff3ea19ebda
> 
> @rawatakhilesh Thanks for pointing this out. Will look into it.

**Comment by AkshayeAnithaPradeep** [comment]
> Okay. So, are you going to push the changes to this branch or a new one?
> 
> > > This post presents some ideas:
> > > https://medium.freecodecamp.org/how-to-securely-store-api-keys-4ff3ea19ebda
> > 
> > 
> > @rawatakhilesh Thanks for pointing this out. Will look into it.

This one. Don't approve this yet.

**Comment by rawatakhilesh** [comment]
> > Okay. So, are you going to push the changes to this branch or a new one?
> > > > This post presents some ideas:
> > > > https://medium.freecodecamp.org/how-to-securely-store-api-keys-4ff3ea19ebda
> > > 
> > > 
> > > @rawatakhilesh Thanks for pointing this out. Will look into it.
> 
> This one. Don't approve this yet.

Cool.

**Comment by AkshayeAnithaPradeep** [comment]
Merged as part of another branch

**Pull request closed without merging**
